Feat/add simple layout
Linyshka/Weather-App pull request #2
Opened 2024-02-04 19:59 UTC by Linyshka

## Выполнено

- Созданы все примерные компоненты без их стилизации

## Скриншоты

![](https://github.com/Linyshka/Weather-App/assets/92429718/3b8c17f7-08cc-4f1a-99ee-412aba859657)
![](https://github.com/Linyshka/Weather-App/assets/92429718/7bd5279a-0d1c-4759-a8be-61664fa64dfc)
![](https://github.com/Linyshka/Weather-App/assets/92429718/c2d21baa-ba0e-44b7-99dd-842c3bf6c487)

## Проблемы

Проблемы с названиями компонентов и скорее всего с архитектурой))

2024-02-05 10:18 UTC, PolinaPolina94 commented
По-моему все хорошо. Единственное, попросили использовать aliases, у себя тоже поправила 🙂

2024-02-05 19:10 UTC, PolinaPolina94 approved these changes

2024-02-06 09:37 UTC, fatykhava requested changes

2024-02-06 09:37 UTC, fatykhava commented on src/App.tsx
> +      <hr />
`<hr /> <br /> `лучше стараться не использовать

2024-02-06 09:37 UTC, fatykhava commented on src/components/DayItem/DayItem.tsx
> +type DayProps = {
лучше выносить типы в отдельный файл на уровне с компонентой

2024-02-06 09:37 UTC, fatykhava commented on src/components/LocationWidget/LocationWidget.tsx
> +    <div style={{ border: "1px solid black", width: "500px" }}>
инлайн стили лучше не использовать, попробуй модульные

2024-02-06 09:37 UTC, fatykhava commented on src/components/PropertyItem/PropertyItem.tsx
> +      <h1>{item.title}</h1>
сколько заголовков h1 может быть на странице?

2024-02-06 09:37 UTC, fatykhava commented on src/components/TimeItem/TimeItem.tsx
> +      <h2>{item.time}</h2>
как будто семантически это вообще не заголовок а просто span

2024-02-06 09:37 UTC, fatykhava commented on src/components/TodayForecast/TodayForecast.tsx
> +      <h2>18&deg;</h2>
и это просто span

2024-02-06 09:37 UTC, fatykhava commented on src/components/WeatherProperties/WeatherProperties.tsx
> +      {weatherProperties.map((property, index) => <PropertyItem key={index} item={property}/> )}
как будто можно было и не выносить)

2024-02-06 11:11 UTC, fatykhava approved these changes

2024-02-06 11:11 UTC, merged